language: node_js
sudo: false
dist: trusty
node_js:
  - "stable"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
env:
  - CHROME_BIN=/usr/bin/google-chrome-beta