language: node_js
sudo: false
dist: trusty
node_js:
  - "stable"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-unstable
env:
  - CHROME_PATH=/usr/bin/google-chrome-unstable
branches:
  only:
  - master
# deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  local-dir: docs-output
#  keep-history: true
#  on:
#    branch: master
script:
  - yarn run test
#  - yarn run document