language: node_js
sudo: false
dist: trusty
node_js:
  - "stable"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
env:
  - CHROME_BIN=/usr/bin/google-chrome-beta
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs-output
  keep-history: true
  on:
    branch: master
script:
  - npm run test
  - npm run document