language: node_js
sudo: required
dist: trusty
node_js:
  - "stable"
addons:
  chrome: stable
env:
  - CHROME_PATH=/usr/bin/google-chrome
branches:
  only:
  - master
# deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  local-dir: docs-output
#  keep-history: true
#  on:
#    branch: master
script:
  - yarn run test
#  - yarn run document
